---
# tasks file for nginx


- name: Instalacao Nginx
  apt:
    name: nginx
    state: present

- name: Arquivos de Configuracao Personalizados
  template:
    src:  nginx.conf
    dest: /etc/nginx/nginx.conf
- name: Security
  template:
    src:  security.conf
    dest: /etc/nginx/security.conf
- name: general.conf
  template:
    src:  general.conf
    dest: /etc/nginx/general.conf
- name: Configuracoes Magento Vhost Personalizado
  template:
    src: magento.conf
    dest: /etc/nginx/magento.conf
- name: PHP Fastcgi
  template:
    src: php_fastcgi.conf
    dest: /etc/nginx/php_fastcgi.conf

- name: Configurando Vhost
  template:
    src: mag.vhost
    dest: /etc/nginx/sites-available/{{ dominio_site }}.conf


- name: Ativando Vhost
  file:
    src: /etc/nginx/sites-available/{{ dominio_site }}.conf
    dest: /etc/nginx/sites-enabled/{{ dominio_site }}.conf
    state: link

- name: Diretorio Site
  file:
    path: "{{ diretorio_site }}"
    state: directory
    owner: www-data #"{{ user }}"
    group: www-data #"{{ group }}"

- name: Remocao Vhost Default
  file:
    path: /etc/nginx/sites-enabled/default 
    state: absent  
    
- name: Remocao Vhost Default
  file:
    path: /etc/nginx/sites-available/default 
    state: absent
  notify: restart nginx

