# Credenciais Banco de Dados MySQL
db_user: user
db_user_password: 654321
db_name: db-default
mysql_root_password: senharoot

# Configuracoes Loja
dominio_site: site.com.br
diretorio_site: /var/www/{{ dominio_site }}
email: exemplo@email.com
diretorio_ssl: /etc/letsencrypt/live/{{ dominio_site }}

# User sftp
user_mag: lojaexemplo
group_mag: lojaexemplo

# Addons  y=sim n=nao 
ssl: y
install_magento2: y

#VersaoPHPDefault
versao_php: "7.4"

diretorio_projeto: "$PWD"

# Restart Services
php_restart: "/etc/init.d/php{{versao_php}}-fpm restart"
nginx_restart: "/etc/init.d/nginx restart"
mysql_restart: "/etc/init.d/mysql restart"