---
- name: Verificando SSL
  stat: path=/etc/letsencrypt/live/www.{{diretorio_ssl}}
  register: stat_result
- name: Instalando SSL
  shell: certbot --nginx -d www."{{ dominio_site }}" -d "{{ dominio_site }}" --non-interactive --agree-tos -m {{ email }}
  when: not stat_result.stat.exists