
- name: Pacotes Basicos
  apt:
    name: software-properties-common
    state: present 

- name: Add Repositorio PHP 
  ansible.builtin.apt_repository:
    repo: 'ppa:ondrej/php'
  
- name: Instalando PHP
  apt:
    name:
      - php{{ versao_php }}
      - php{{ versao_php }}-fpm
      - php{{ versao_php }}-common
      - php{{ versao_php }}-mysql
      - php{{ versao_php }}-gmp
      - php{{ versao_php }}-curl
      - php{{ versao_php }}-intl
      - php{{ versao_php }}-mbstring
      - php{{ versao_php }}-xmlrpc
      - php{{ versao_php }}-gd
      - php{{ versao_php }}-xml
      - php{{ versao_php }}-cli
      - php{{ versao_php }}-zip
      - php{{ versao_php }}-bcmath
      - php{{ versao_php }}-ctype
      - php{{ versao_php }}-dom
      - php{{ versao_php }}-iconv
      - php{{ versao_php }}-simplexml
      - php{{ versao_php }}-soap
      - php{{ versao_php }}-xsl
      - php{{ versao_php }}-sockets
      - php{{ versao_php }}-redis
      - php{{ versao_php }}-opcache
    state: latest
    update_cache: true
  


- copy:
    src: ./php.ini
    dest: /etc/php/7.4/fpm/php-mag.ini
    owner: root
    group: root
          
- name: Configurando POOL FPM 
  template:
    src: ./mag-pool.conf
    dest: /etc/php/{{ versao_php }}/fpm/pool.d/mag-pool.conf
    notify: restart php


    