- hosts: all 
  become: true
  roles:
    - mysql
    - php
    - composer
    - nginx
  
  # Variaveis personalizaveis
  # Definicao de dominio, email, usuarios 
  vars_files:
    - /home/projeto/ansible/vars/vars.yml